test2

diff --git a/.github/workflows/build-and-run-example-project.yml b/.github/workflows/build-and-run-example-project.yml
--- a/.github/workflows/build-and-run-example-project.yml
+++ b/.github/workflows/build-and-run-example-project.yml
@@ -26,11 +26,15 @@ jobs:
           java-version: '8'
           distribution: 'temurin'
 
+      - name: Create Logs Directory
+        run: mkdir -p logs
+
       - name: Update Version in pom.xml
         run: mvn versions:set -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false
 
       - name: Build and Install Plugin
-        run: mvn install
+        run: |
+          mvn install > logs/build.log 2>&1 || { cat logs/build.log; exit 1; }
 
       - name: Upload Plugin Artifact
         id: upload-artifact
@@ -39,6 +43,13 @@ jobs:
           name: smart-doc-maven-jar
           path: ~/.m2/repository/com/ly/smart-doc
           if-no-files-found: error
+
+      - name: Upload Build Log
+        if: failure()  # Only run if previous steps fail
+        uses: actions/upload-artifact@v4
+        with:
+          name: smart-doc-build-log
+          path: logs
 
   maven-plugin-build:
     needs: build
@@ -60,6 +71,9 @@ jobs:
           java-version: '8'
           distribution: 'temurin'
 
+      - name: Create Logs Directory
+        run: mkdir -p logs
+
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
@@ -79,7 +93,8 @@ jobs:
           mvn versions:set-property -Dproperty="smart-doc.version" -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false
 
       - name: Build and Install
-        run: mvn -DskipTests=true install
+        run: |
+          mvn -DskipTests=true install > logs/install-plugin.log 2>&1 || { cat logs/install-plugin.log; exit 1; }
 
       - name: Upload Plugin Artifact
         id: upload-artifact
@@ -88,6 +103,13 @@ jobs:
           name: smart-doc-maven-plugin-jar
           path: ~/.m2/repository/com/ly/smart-doc
           if-no-files-found: error
+
+      - name: Upload Plugin Build Log
+        if: failure() # Only run if previous steps fail
+        uses: actions/upload-artifact@v4
+        with:
+          name: maven-plugin-build-logs
+          path: logs
 
   generate-api-docs:
     needs: maven-plugin-build
@@ -112,6 +134,9 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
+      - name: Create Logs Directory
+        run: mkdir -p logs
+
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
@@ -131,35 +156,36 @@ jobs:
           mvn versions:set-property -Dproperty="smart-doc.version" -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false
 
       - name: Build and Install Example Project
-        run: mvn -DskipTests=true install
+        run: |
+          mvn -DskipTests=true install > logs/build-example-project.log 2>&1 || { cat logs/build-example-project.log; exit 1; }
 
       - name: Generate ${{ matrix.doc_type }} API Documentation
         run: |
           case ${{ matrix.doc_type }} in
             rest)
-              mvn -DskipTests=true smart-doc:adoc
-              mvn -DskipTests=true smart-doc:html
-              mvn -DskipTests=true smart-doc:jmeter
-              mvn -DskipTests=true smart-doc:markdown
-              mvn -DskipTests=true smart-doc:openapi
-              mvn -DskipTests=true smart-doc:postman
-              mvn -DskipTests=true smart-doc:word
-              mvn test -Dtest=com.power.doc.torna.TornaApiTest
+              mvn -DskipTests=true smart-doc:adoc > logs/rest-adoc.log 2>&1 || { cat logs/rest-adoc.log; exit 1; }
+              mvn -DskipTests=true smart-doc:html > logs/rest-html.log 2>&1 || { cat logs/rest-html.log; exit 1; }
+              mvn -DskipTests=true smart-doc:jmeter > logs/rest-jmeter.log 2>&1 || { cat logs/rest-jmeter.log; exit 1; }
+              mvn -DskipTests=true smart-doc:markdown > logs/rest-markdown.log 2>&1 || { cat logs/rest-markdown.log; exit 1; }
+              mvn -DskipTests=true smart-doc:openapi > logs/rest-openapi.log 2>&1 || { cat logs/rest-openapi.log; exit 1; } 
+              mvn -DskipTests=true smart-doc:postman > logs/rest-postman.log 2>&1 || { cat logs/rest-postman.log; exit 1; }
+              mvn -DskipTests=true smart-doc:word > logs/rest-word.log 2>&1 || { cat logs/rest-word.log; exit 1; } 
+              mvn test -Dtest=com.power.doc.torna.TornaApiTest > logs/rest-TornaApiTest.log 2>&1 || { cat logs/rest-TornaApiTest.log; exit 1; } 
               ;;
             dubbo)
-              mvn -DskipTests=true smart-doc:rpc-adoc
-              mvn -DskipTests=true smart-doc:rpc-html
-              mvn -DskipTests=true smart-doc:rpc-markdown
+              mvn -DskipTests=true smart-doc:rpc-adoc > logs/dubbo-doc.adoc 2>&1 || { cat logs/dubbo-doc.adoc; exit 1; }
+              mvn -DskipTests=true smart-doc:rpc-html > logs/dubbo-html.log 2>&1 || { cat logs/dubbo-html.log; exit 1; }
+              mvn -DskipTests=true smart-doc:rpc-markdown > logs/dubbo-markdown.log 2>&1 || { cat logs/dubbo-markdown.log; exit 1; }
               ;;
             javadoc)
-              mvn -DskipTests=true smart-doc:javadoc-adoc
-              mvn -DskipTests=true smart-doc:javadoc-html
-              mvn -DskipTests=true smart-doc:javadoc-markdown
+              mvn -DskipTests=true smart-doc:javadoc-adoc > logs/javadoc-adoc.log 2>&1 || { cat logs/javadoc-adoc.log; exit 1; }
+              mvn -DskipTests=true smart-doc:javadoc-html > logs/javadoc-html.log 2>&1 || { cat logs/javadoc-html.log; exit 1; }
+              mvn -DskipTests=true smart-doc:javadoc-markdown > logs/javadoc-markdown.log 2>&1 || { cat logs/javadoc-markdown.log; exit 1; }
               ;;
             websocket)
-              mvn -DskipTests=true smart-doc:websocket-adoc
-              mvn -DskipTests=true smart-doc:websocket-html
-              mvn -DskipTests=true smart-doc:websocket-markdown
+              mvn -DskipTests=true smart-doc:websocket-adocc > logs/websocket-adocc.log 2>&1 || { cat logs/websocket-adocc.log; exit 1; }
+              mvn -DskipTests=true smart-doc:websocket-html > logs/websocket-html.log 2>&1 || { cat logs/websocket-html.log; exit 1; }
+              mvn -DskipTests=true smart-doc:websocket-markdown > logs/websocket-markdown.log 2>&1 || { cat logs/websocket-markdown.log; exit 1; }
               ;;
           esac
 
@@ -169,6 +195,13 @@ jobs:
           name: ${{ matrix.doc_type }}-api-doc
           path: ${{ github.workspace }}/target/doc/
           if-no-files-found: error
+
+      - name: Upload API Documentation Log
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.doc_type }}-api-doc-log
+          path: logs
 
   generate-grpc-api-doc:
     needs: maven-plugin-build
@@ -192,6 +225,9 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+
+      - name: Create Logs Directory
+        run: mkdir -p logs
 
       - name: Download Artifact
         uses: actions/download-artifact@v4
@@ -218,16 +254,18 @@ jobs:
           mvn versions:set-property -Dproperty="smart-doc.version" -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false
 
       - name: Build and Install Example Project
-        run: mvn -DskipTests=true install
+        run: |
+          mvn -DskipTests=true install > build.log 2>&1 || { cat build.log; exit 1; }
 
       - name: Generate gRPC AsciiDoc Documentation
-        run: mvn -DskipTests=true smart-doc:grpc-adoc
+        run: | 
+          mvn -DskipTests=true smart-doc:grpc-adoc > logs/grpc-adoc.log 2>&1 || { cat logs/grpc-adoc.log; exit 1; }
 
       - name: Generate gRPC HTML Documentation
-        run: mvn -DskipTests=true smart-doc:grpc-html
+        run: mvn -DskipTests=true smart-doc:grpc-html > logs/grpc-html.log 2>&1 || { cat logs/grpc-html.log; exit 1; }
 
       - name: Generate gRPC Markdown Documentation
-        run: mvn -DskipTests=true smart-doc:grpc-markdown
+        run: mvn -DskipTests=true smart-doc:grpc-markdown > logs/grpc-markdown.log 2>&1 || { cat logs/grpc-markdown.log; exit 1; }
 
       - name: Upload gRPC API Documentation
         uses: actions/upload-artifact@v4
@@ -235,3 +273,10 @@ jobs:
           name: gRPC-api-doc-${{ runner.os }}
           path: ${{ github.workspace }}/target/doc/
           if-no-files-found: error
+
+      - name: Upload API Documentation Log
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: grpc-api-doc-log
+          path: logs
